<div class="row">
	<div class="col-md-12">
	
		<div class="panel panel-default">
		
        	<div class="panel-heading">
        	
        		<h3 class="panel-title">Requests</h3>

        	</div>
        	
        	<div class="panel-body">
        	
        		<p>first request</p>
        		
        	</div>

		</div>

	</div>

</div>
<div class="row">
	<div class="col-md-12">
	
		<div class="panel panel-default">
		
        	<div class="panel-heading">
        	
        		<h3 class="panel-title">Contracts</h3>

        	</div>
        	
        	<div class="panel-body">
        	
        		<p>first contract</p>
        		
        	</div>

		</div>

	</div>

</div>