<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sGPB Portal%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate(''), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Portal Guide') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Acquiring') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Create new contracts. Tracking contracts. Build reports.'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Acquiring') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Salary contracts') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Check salary registries. Execute new card registry'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Salary contracts') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Military') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Send registry for military'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Military') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
